# folder of files to read in
in_dir: 'E:\Zooniverse Clips\Tutorial\whales and ships\20-second clips_full bandwidth'
# folder to put decimated MP3 and wav files
out_mp3: 'E:\Zooniverse Clips\Tutorial\whales and ships\decimp3_thresh_30_-50_zmin_-20_zmax_0'
out_wav: 'deciwav'
# whether or not to delete decimated .wav files and out_wav folder
delete_wav: True
# target SR for MP3 - 44.1kHz is standard audio format
mp3_sr_hz: 44100
# filter settings
high_filt_hz: 2000
low_filt_hz: 100
# normalizing - 'fixed', 'max', or 'threshold'. 
# 'fixed' adds the same dB value (norm_value) to each wav file
# 'max' adjusts each file to the max value, here norm_value is 
# how close (in dB) to get to max. E.g. norm_value 5 means 5dB less
# than max volume, higher numbers are quieter in this case.
# 'threshold' adds the same dB value like 'fixed', but the result
# will not go higher than a specified threshold value. For this
# norm_value must be a list of two numbers e.g. [20, -15] will add
# 20dB, but the result will be capped at -15dB
norm_type: 'threshold'
norm_value: [30, -50]
# which channel to use for mp3 and spectrogram
channel: 1
# Logical flag to make plots 
do_plot: True
# spectrogram params - these are taken from Anne's R code
spec_config: {
    nfft: 6442,
    overlap: .9,
    width: 1400,
    height: 700,
    zmin: -20,
    zmax: 0,
    fmin: 100,
    fmax: 2000,
    out_spec: 'E:\Zooniverse Clips\Tutorial\whales and ships\decimp3_thresh_30_-50_zmin_-20_zmax_0',
    q_scale: FALSE,
    q: [0, 1]
}
# print debug stuff
debug: False